### ISSUE TITLE
[Suggestion] Ability to upload data to katb.in from command line via curl

### ISSUE THREAD

**Issue by tur1ngb0x** [ATechnoHazard/katbin#5]
It would be nice to have a functionality similar to

`$ command | curl -F 'f:1=<-' ix.io`

example

`$ cat /etc/fstab | curl -F 'f:1=<-' ix.io`

output
http://ix.io/3ukb

**Comment by SphericalKat** [comment]
`curl -X POST https://katb.in/api/paste --data-binary "paste[content]=$(cat log.txt)"`
